import turtle

def sailboat():
    turtle.up()
    turtle.fillcolor("Blue")
    turtle.left(180)
    turtle.begin_fill()
    turtle.down()
    turtle.forward(1000)
    turtle.left(90)
    turtle.forward(1000)
    turtle.left(90)
    turtle.forward(2000)
    turtle.left(90)
    turtle.forward(1000)
    turtle.left(90)
    turtle.forward(1000)
    turtle.left(90)
    turtle.end_fill()
    turtle.up()
    turtle.goto(400, 300)
    turtle.fillcolor("Yellow")
    turtle.begin_fill()
    turtle.down()
    turtle.circle(50)
    turtle.end_fill()
    turtle.up()
    turtle.goto(0, 0)
    turtle.fillcolor("White")
    turtle.down()
    turtle.begin_fill()
    turtle.forward(40)
    turtle.left(270)
    turtle.forward(80)
    turtle.left(230)
    turtle.forward(125)
    turtle.right(140)
    turtle.forward(80)
    turtle.end_fill()
    turtle.up()
    turtle.forward(15)
    turtle.fillcolor("Brown")
    turtle.down()
    turtle.begin_fill()
    turtle.left(270)
    turtle.forward(80)
    turtle.left(-230)
    turtle.forward(60)
    turtle.left(50)
    turtle.forward(160)
    turtle.left(50)
    turtle.forward(60)
    turtle.left(490)
    turtle.forward(160)
    turtle.end_fill()
    turtle.up()
    turtle.hideturtle()

def main():
    turtle.speed(0)
    turtle.bgcolor("Light Blue")
    turtle.pencolor("Black")
    turtle.pensize(2.5)
    sailboat()
    input("Press enter to exit: ")

main()

#DONE.