#AUTHOR: MYI

import turtle
t = turtle

def draw_squares(length):
    og_length = length
    t.pensize(2.5)
    t.speed(0)
    t.penup()
    t.goto(-300, -300)
    t.fillcolor("Red")
    t.pendown()
    t.begin_fill()
    t.forward(og_length)
    t.left(90)
    t.forward(og_length)
    t.left(90)
    t.forward(og_length)
    t.left(90)
    t.forward(og_length)
    t.left(90)
    t.end_fill()
    t.penup()
    t.forward(og_length / 2)
    t.fillcolor("Orange")
    t.pendown()
    t.setheading(45)
    t.begin_fill()
    t.forward(og_length / 1.42)
    t.left(90)
    t.forward(og_length / 1.42)
    t.left(90)
    t.forward(og_length / 1.42)
    t.left(90)
    t.forward(og_length / 1.42)
    t.left(90)
    t.end_fill()
    t.penup()
    t.forward(og_length / 2.84)
    t.fillcolor("Yellow")
    t.setheading(0)
    t.pendown()
    t.begin_fill()
    t.left(90)
    t.forward(og_length / 2.01)
    t.left(90)
    t.forward(og_length / 2.01)
    t.left(90)
    t.forward(og_length / 2.01)
    t.left(90)
    t.forward(og_length / 2.01)
    t.left(90)
    t.end_fill()
    t.penup()
    t.forward(og_length / 4.02)
    t.fillcolor("Green")
    t.pendown()
    t.setheading(135)
    t.begin_fill()
    t.forward(og_length / 2.85)
    t.left(90)
    t.forward(og_length / 2.85)
    t.left(90)
    t.forward(og_length / 2.85)
    t.left(90)
    t.forward(og_length / 2.85)
    t.left(90)
    t.end_fill()
    t.penup()
    t.forward(og_length / 5.70)
    t.setheading(0)
    t.left(180)
    t.fillcolor("Blue")
    t.begin_fill()
    t.pendown()
    t.forward(og_length / 4.05)
    t.left(90)
    t.forward(og_length / 4.05)
    t.left(90)
    t.forward(og_length / 4.05)
    t.left(90)
    t.forward(og_length / 4.05)
    t.left(90)
    t.end_fill()
    t.penup()
    t.forward(og_length / 8.1)
    t.setheading(225)
    t.fillcolor("Purple")
    t.begin_fill()
    t.pendown()
    t.forward(og_length / 5.78)
    t.left(90)
    t.forward(og_length / 5.78)
    t.left(90)
    t.forward(og_length / 5.78)
    t.left(90)
    t.forward(og_length / 5.78)
    t.left(90)
    t.end_fill()
    t.penup()
    t.hideturtle()
    return ("Smallest Square Length: ",og_length / 5.78)

def main():
    input("START?")
    x = draw_squares(600)
    print(x)
    input("EXIT?")

main()