#AUTHOR: MYI

import turtle
t = turtle

def draw_squares(length):
    original_length = length
    ending_length = original_length / 6
    t.pensize(2.5)
    t.speed(0)
    t.penup()
    t.fillcolor("RED")
    t.goto(-300, -300)
    t.pendown()
    t.begin_fill()
    t.forward(original_length)
    t.left(90)
    t.forward(original_length)
    t.left(90)
    t.forward(original_length)
    t.left(90)
    t.forward(original_length)
    t.left(90)
    t.end_fill()
    t.penup()
    t.fillcolor("ORANGE")
    t.forward(300)
    t.setheading(45)
    t.pendown()
    t.begin_fill()
    t.forward(425)
    t.left(90)
    t.forward(425)
    t.left(90)
    t.forward(425)
    t.left(90)
    t.forward(425)
    t.left(90)
    t.end_fill()
    t.penup()
    t.fillcolor("YELLOW")
    t.forward(212.5)
    t.setheading(0)
    t.pendown()
    t.begin_fill()
    t.left(90)
    t.forward(300)
    t.left(90)
    t.forward(300)
    t.left(90)
    t.forward(300)
    t.left(90)
    t.forward(300)
    t.left(90)
    t.end_fill()
    t.penup()
    t.fillcolor("GREEN")
    t.forward(150)
    t.setheading(135)
    t.pendown()
    t.begin_fill()
    t.forward(210)
    t.left(90)
    t.forward(210)
    t.left(90)
    t.forward(210)
    t.left(90)
    t.forward(210)
    t.left(90)
    t.end_fill()
    t.penup()
    t.fillcolor("BLUE")
    t.forward(105)
    t.setheading(0)
    t.pendown()
    t.begin_fill()
    t.left(180)
    t.forward(145)
    t.left(90)
    t.forward(145)
    t.left(90)
    t.forward(145)
    t.left(90)
    t.forward(145)
    t.left(90)
    t.end_fill()
    t.penup()
    t.fillcolor("PURPLE")
    t.forward(72.5)
    t.setheading(225)
    t.pendown()
    t.begin_fill()
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.end_fill()
    t.penup()
    t.hideturtle()
    return ("Smallest Square Length: ",ending_length)

def main():
    input("press enter to start: ")
    x = draw_squares(600)
    print(x)
    input("press enter to exit: ")

main()